stages:
  - test

modelsim:
  stage: test
  # https://github.com/goldenSniperOS/modelsim-docker
  image: goldensniper/modelsim-docker
  script: |
    cd ./modelsim
    vsim -c -do ../scripts/modelsim_compile.tcl
    vsim -c -do ../scripts/modelsim_test.tcl

quartus:
  stage: test
  image: $CI_REGISTRY/leuen4/container_builder/vhdl_rpn-ci
  script: |
    cd ./quartus
    quartus_sh -t ../scripts/quartus_project.tcl
    quartus_sh -t ../scripts/quartus_compile.tcl
  artifacts:
    paths:
      - ./quartus/output_files/*.sof
