default:
  image: ghcr.io/nikleberg/quartus-prime:latest

example:
  stage: test
  before_script: |
    apt-get -q -y update
    apt-get -q -y install net-tools
    ifconfig eth0 down
    ifconfig eth0 hw ether "00:ab:ab:ab:ab:ab"
    ifconfig eth0 up
  script: |
    cd ./modelsim
    vsim -c -do ../scripts/modelsim_compile.tcl
    vsim -c -do ../scripts/modelsim_test.tcl
    cd ./../quartus
    quartus_sh -t ../scripts/quartus_project.tcl
    quartus_sh -t ../scripts/quartus_compile.tcl
  artifacts:
    paths:
      - ./quartus/output_files/*.sof
