default:
  # https://github.com/goldenSniperOS/modelsim-docker
  image: goldensniper/modelsim-docker

stages:
  - test

test:
  stage: test
  script: |
    cd ./modelsim
    vsim -c -do ../scripts/modelsim_compile.tcl
    vsim -c -do ../scripts/modelsim_test.tcl
